In [1]:
import numpy as np

In [2]:
ratio_index_saaty = np.array([0, 0, 0.58, 0.9, 1.12, 1.24, 1.32, 1.41, 1.46, 1.49]) 

In [3]:
# perbandinqan antar kriteria
p_criteria = np.array([
    [1,     1,   3,   1, 3],
    [1,     1,   2,   1, 1],
    [1/3, 1/2,   1,   1, 2],
    [  1,   1,   1,   1, 3],
    [1/3,   1, 1/2, 1/3, 1]
])

# perbandingan antar alternatif
p_alternatives = np.array([
    # kriteria C01
    [
        [  1,   3, 3],
        [1/3,   1, 2],
        [1/3, 1/2, 1]
    ],
    # kriteria C02
    [
        [  1,   2, 4],
        [1/2,   1, 3],
        [1/4, 1/3, 1]
    ],
    # kriteria C03
    [
        [  1,   2, 1],
        [1/2,   1, 2],
        [  1, 1/2, 1]
    ],
    # kriteria C04
    [
        [  1,   2, 3],
        [1/2,   1, 6],
        [1/3, 1/6, 1]
    ],
    # kriteria C05
    [
        [  1,   4, 3],
        [1/4,   1, 2],
        [1/3, 1/2, 1]
    ]
])

In [4]:
print(p_criteria.shape)
print(p_alternatives.shape)

(5, 5)
(5, 3, 3)


In [5]:
p_total = np.sum(p_criteria, axis=0)
p_total

array([ 3.66666667,  4.5       ,  7.5       ,  4.33333333, 10.        ])

In [6]:
p_priority = p_criteria / p_total
p_priority

array([[0.27272727, 0.22222222, 0.4       , 0.23076923, 0.3       ],
       [0.27272727, 0.22222222, 0.26666667, 0.23076923, 0.1       ],
       [0.09090909, 0.11111111, 0.13333333, 0.23076923, 0.2       ],
       [0.27272727, 0.22222222, 0.13333333, 0.23076923, 0.3       ],
       [0.09090909, 0.22222222, 0.06666667, 0.07692308, 0.1       ]])

In [7]:
p_priority_weight = np.mean(p_priority, axis=1)
p_priority_weight

array([0.28514375, 0.21847708, 0.15322455, 0.23181041, 0.11134421])

In [8]:
p_consistency = np.dot(p_criteria, p_priority_weight) / p_priority_weight
p_consistency

array([5.36269006, 5.27846931, 5.299476  , 5.27451901, 5.19785997])

In [9]:
n = p_criteria.shape[0]
lambda_max = np.mean(p_consistency)

RI = ratio_index_saaty[n]
CI = (lambda_max - n) / (n - 1)
CR = CI / RI

# Konsisten apabila 0 < CR < 0.1 
print(CR)

0.05697638478475637


In [10]:
p_rank = np.array([np.mean(p_alternatives[i] / np.sum(p_alternatives[i], axis=0), axis=1) for i in range(p_alternatives.shape[0])]).T
p_rank

array([[0.58888889, 0.55714286, 0.40714286, 0.4923445 , 0.61961722],
       [0.25185185, 0.3202381 , 0.32857143, 0.39617225, 0.22434875],
       [0.15925926, 0.12261905, 0.26428571, 0.11148325, 0.15603402]])

In [11]:
final_decision = np.dot(p_rank, p_priority_weight)
final_decision

array([0.53514658, 0.30894066, 0.15591276])

In [12]:
print(f"Alternatif terbaik: A0{np.argmax(final_decision) + 1}")

Alternatif terbaik: A01
